
import 'package:get/get.dart';

class AppTranslations extends Translations {
  @override
  Map<String, Map<String, String>> get keys => {
        'en': {
          'enterPassword': 'Enter Password',
          'password': 'Password',
          'cancel': 'Cancel',
          'incorrecpassword':'Incorrect password',
          'submit': 'Submit',
          'scanHere': 'Scan Here!',
          'scanningInProgress': 'Scanning in Progress',
          'enterCode': 'Enter code',
          'productNotFound': 'Product not found.',
          'permissionDenied': 'Permission Denied',
          'storagePermissionIsRequired': 'Storage permission is required.',
          'openSettings': 'Open Settings',
          'pleaseSelectAnImage': 'Please select an image.',
          'productAddedSuccessfully': 'Product added successfully!',
          'excelUploadedSuccessfully': 'Excel uploaded successfully!',
          'failedToGetFilePath': 'Failed to get file path.',
          'addProduct': 'Add Product',
          'barcode': 'Barcode',
          'brand': 'Brand',
          'category': 'Category',
          'item': 'Item',
          'description': 'Description',
          'unit': 'Unit',
          'unitPrice': 'Unit Price',
          'uploadExcel': 'Upload Excel',
          'pleaseEnterABarcode': 'Please enter a barcode',
          'pleaseEnterABrand': 'Please enter a brand',
          'pleaseEnterACategory': 'Please enter a category',
          'pleaseEnterAnItem': 'Please enter an item',
          'pleaseEnterADescription': 'Please enter a description',
          'pleaseEnterAUnit': 'Please enter a unit',
          'pleaseEnterAQuantity': 'Please enter a quantity',
          'pleaseEnterAUnitPrice': 'Please enter a unit price',
          'addManually': 'Add Manually',
          'downloadExcel': 'Download Excel',
          'hereIsYourExcelFile': 'Here is your Excel file!',
          'noImageSelected': 'No image selected',
          'management': 'Management',
          'viewData': 'View Data',
          'scanView': 'Scan View',
          'detailsOfScannedItem': 'Details of Scanned Items',
          'barcodeLabel': 'Barcode : ',
          'brandLabel': 'Brand : ',
          'categoryLabel': 'Category : ',
          'itemLabel': 'Item : ',
          'descriptionLabel': 'Description : ',
          'unitLabel': 'Unit : ',
          'unitPriceLabel': 'Unit Price : ',
          'welcome': 'Welcome To Price Checker App!',
          'ourAppHelpsYou': 'Our app helps you to easily scan different products \n           view price, brand, description and more',
        },
        'ar': {
          'enterPassword': 'أدخل كلمة المرور',
          'password': 'كلمة المرور',
          'cancel': 'إلغاء',
          'incorrecpassword':'كلمة المرور غير صحيحة',
          'submit': 'إرسال',
          'scanHere': 'امسح هنا!',
          'scanningInProgress': 'جاري المسح',
          'enterCode': 'أدخل الرمز',
          'productNotFound': 'لم يتم العثور على المنتج.',
          'permissionDenied': 'تم رفض الإذن',
          'storagePermissionIsRequired': 'الإذن بالتخزين مطلوب.',
          'openSettings': 'فتح الإعدادات',
          'pleaseSelectAnImage': 'يرجى اختيار صورة.',
          'productAddedSuccessfully': 'تم إضافة المنتج بنجاح!',
          'excelUploadedSuccessfully': 'تم تحميل ملف Excel بنجاح!',
          'failedToGetFilePath': 'فشل في الحصول على مسار الملف.',
          'addProduct': 'إضافة منتج',
          'barcode': 'الباركود',
          'brand': 'العلامة التجارية',
          'category': 'الفئة',
          'item': 'البند',
          'description': 'الوصف',
          'unit': 'الوحدة',
          'unitPrice': 'سعر الوحدة',
          'uploadExcel': 'تحميل Excel',
          'pleaseEnterABarcode': 'يرجى إدخال باركود',
          'pleaseEnterABrand': 'يرجى إدخال علامة تجارية',
          'pleaseEnterACategory': 'يرجى إدخال فئة',
          'pleaseEnterAnItem': 'يرجى إدخال بند',
          'pleaseEnterADescription': 'يرجى إدخال وصف',
          'pleaseEnterAUnit': 'يرجى إدخال وحدة',
          'pleaseEnterAQuantity': 'يرجى إدخال كمية',
          'pleaseEnterAUnitPrice': 'يرجى إدخال سعر الوحدة',
          'addManually': 'إضافة يدويًا',
          'downloadExcel': 'تنزيل Excel',
          'hereIsYourExcelFile': 'ها هو ملف Excel الخاص بك!',
          'noImageSelected': 'لم يتم اختيار أي صورة',
          'management': 'الإدارة',
          'viewData': 'عرض البيانات',
          'scanView': 'عرض المسح',
          'detailsOfScannedItem': 'تفاصيل العناصر الممسوحة',
          'barcodeLabel': 'الباركود: ',
          'brandLabel': 'العلامة التجارية: ',
          'categoryLabel': 'الفئة: ',
          'itemLabel': 'البند: ',
          'descriptionLabel': 'الوصف: ',
          'unitLabel': 'الوحدة: ',
          'unitPriceLabel': 'سعر الوحدة: ',
          'welcome': 'مرحبًا بك في تطبيق فحص الأسعار!',
          'ourAppHelpsYou': 'يساعدك تطبيقنا على مسح المنتجات المختلفة بسهولة \n           عرض السعر والعلامة التجارية والوصف والمزيد',
        },
      };

}
